"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.seedDashboardData = exports.importCollections = exports.applyChargeModel = exports.closeExpenseRequest = exports.recordDisbursement = exports.recordApproval = exports.withdrawExpenseRequest = exports.scheduleSnag = exports.submitExpenseRequest = exports.createMaintenanceRequest = exports.markInstancePaid = exports.generateRecurringInstances = exports.scheduledRecurring = exports.recomputeBalances = exports.recordPayment = exports.removeMembership = exports.updateMembership = exports.inviteUsersBulk = exports.inviteUser = exports.createSociety = exports.refreshClaims = exports.ping = void 0;
const app_1 = require("firebase-admin/app");
const v2_1 = require("firebase-functions/v2");
(0, app_1.initializeApp)();
(0, v2_1.setGlobalOptions)({ region: 'asia-south1' });
var ping_1 = require("./callable/ping");
Object.defineProperty(exports, "ping", { enumerable: true, get: function () { return ping_1.ping; } });
var refreshClaims_1 = require("./callable/refreshClaims");
Object.defineProperty(exports, "refreshClaims", { enumerable: true, get: function () { return refreshClaims_1.refreshClaims; } });
var createSociety_1 = require("./callable/createSociety");
Object.defineProperty(exports, "createSociety", { enumerable: true, get: function () { return createSociety_1.createSociety; } });
var inviteUser_1 = require("./callable/inviteUser");
Object.defineProperty(exports, "inviteUser", { enumerable: true, get: function () { return inviteUser_1.inviteUser; } });
var inviteUsersBulk_1 = require("./callable/inviteUsersBulk");
Object.defineProperty(exports, "inviteUsersBulk", { enumerable: true, get: function () { return inviteUsersBulk_1.inviteUsersBulk; } });
var updateMembership_1 = require("./callable/updateMembership");
Object.defineProperty(exports, "updateMembership", { enumerable: true, get: function () { return updateMembership_1.updateMembership; } });
var removeMembership_1 = require("./callable/removeMembership");
Object.defineProperty(exports, "removeMembership", { enumerable: true, get: function () { return removeMembership_1.removeMembership; } });
var recordPayment_1 = require("./callable/recordPayment");
Object.defineProperty(exports, "recordPayment", { enumerable: true, get: function () { return recordPayment_1.recordPayment; } });
var recomputeBalances_1 = require("./trigger/recomputeBalances");
Object.defineProperty(exports, "recomputeBalances", { enumerable: true, get: function () { return recomputeBalances_1.recomputeBalances; } });
var scheduledRecurring_1 = require("./scheduled/scheduledRecurring");
Object.defineProperty(exports, "scheduledRecurring", { enumerable: true, get: function () { return scheduledRecurring_1.scheduledRecurring; } });
Object.defineProperty(exports, "generateRecurringInstances", { enumerable: true, get: function () { return scheduledRecurring_1.generateRecurringInstances; } });
var markInstancePaid_1 = require("./callable/markInstancePaid");
Object.defineProperty(exports, "markInstancePaid", { enumerable: true, get: function () { return markInstancePaid_1.markInstancePaid; } });
var createMaintenanceRequest_1 = require("./callable/createMaintenanceRequest");
Object.defineProperty(exports, "createMaintenanceRequest", { enumerable: true, get: function () { return createMaintenanceRequest_1.createMaintenanceRequest; } });
var submitExpenseRequest_1 = require("./callable/submitExpenseRequest");
Object.defineProperty(exports, "submitExpenseRequest", { enumerable: true, get: function () { return submitExpenseRequest_1.submitExpenseRequest; } });
var scheduleSnag_1 = require("./callable/scheduleSnag");
Object.defineProperty(exports, "scheduleSnag", { enumerable: true, get: function () { return scheduleSnag_1.scheduleSnag; } });
var withdrawExpenseRequest_1 = require("./callable/withdrawExpenseRequest");
Object.defineProperty(exports, "withdrawExpenseRequest", { enumerable: true, get: function () { return withdrawExpenseRequest_1.withdrawExpenseRequest; } });
var recordApproval_1 = require("./callable/recordApproval");
Object.defineProperty(exports, "recordApproval", { enumerable: true, get: function () { return recordApproval_1.recordApproval; } });
var recordDisbursement_1 = require("./callable/recordDisbursement");
Object.defineProperty(exports, "recordDisbursement", { enumerable: true, get: function () { return recordDisbursement_1.recordDisbursement; } });
var closeExpenseRequest_1 = require("./callable/closeExpenseRequest");
Object.defineProperty(exports, "closeExpenseRequest", { enumerable: true, get: function () { return closeExpenseRequest_1.closeExpenseRequest; } });
var applyChargeModel_1 = require("./callable/applyChargeModel");
Object.defineProperty(exports, "applyChargeModel", { enumerable: true, get: function () { return applyChargeModel_1.applyChargeModel; } });
var importCollections_1 = require("./callable/importCollections");
Object.defineProperty(exports, "importCollections", { enumerable: true, get: function () { return importCollections_1.importCollections; } });
var seedDashboardData_1 = require("./callable/seedDashboardData");
Object.defineProperty(exports, "seedDashboardData", { enumerable: true, get: function () { return seedDashboardData_1.seedDashboardData; } });
